spring:
  application:
    name: notification

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://notification-db:3308/urecar_notification?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root


server:
  port: 8082


notification:
  key-path: /home/ubuntu/docker/notification/service-account.json