spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/urecar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  data:
    redis:
      host: localhost
      port: 6379
      password: ssafy
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"