spring:
  application:
    name: UreCar

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/urecar?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  token:
    header: Authorization
    secret: 18CB6A32EFEE1C3D5873D7D35F28D18CB6A32EFEE1C3D5873D7D35F28D18CB6A32EFEE1C3D5873D7D35F28D
    access-expired-time: 3000 #10s
    refresh-expired-time: 1209600000 #14d

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  server:
    port: 8081